#! /bin/sh
xsetroot -cursor_name left_ptr
xrdb ~/.Xresources
feh --bg-center --bg-scale ~/space.jpg

#primary autostart
deadd-notification-center &
picom --experimental-backends &
polybar top &
polybar bottom &
# conky &
sxhkd &
gebaard -b

#secondary autostart
nextcloud &
joplin-desktop &
telegram-desktop &

# Config

bspc config border_width         2
bspc config normal_border_color  "#191919"
bspc config focused_border_color "#2F2F2F"
# bspc config normal_border_color  "#f7f8f8"
# bspc config focused_border_color "#f8818e"
# bspc config active_border_color   "#f7f8f8"
bspc config window_gap           14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc config top_padding 25
bspc config bottom_padding 27
bspc config left_padding 3
bspc config right_padding 4

# Monitors
bspc monitor -d term web code music sec msg anki book re

# Rules
bspc rule -a Gnome-calendar state=floating
bspc rule -a blueberry state=floating
bspc rule -a urxvt state=floating
bspc rule -a Customize\ CLion state=floating
bspc rule -a Wine state=floating
bspc rule -a MEGAsync state=floating border=off

bspc rule -a Google-chrome desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a code-oss desktop='^3'
bspc rule -a Deadbeef desktop='^4'
bspc rule -a KeePassXC desktop='^5'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a Anki desktop='^7'

# Layout toggle
setxkbmap -option grp:alt_shift_toggle us,ru

# Shift-home, shift-end
setxkbmap -option numpad:microsoft

# Lock screen
xidlehook \
  --not-when-fullscreen \
  --timer 90 \
    'echo $(xbacklight -get) > /tmp/xidlebacklight; xbacklight -set 1 -time 400 -fps 30' \
    'xbacklight -set $(cat /tmp/xidlebacklight) -time 400 -fps 30; rm /tmp/xidlebacklight' \
  --timer 60 \
    'qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.MainWindow.lockAllDatabases 2> /dev/null; i3lock-fancy' \
    'xbacklight -set $(cat /tmp/xidlebacklight) -time 400 -fps 30; rm /tmp/xidlebacklight' \
  --timer 3600 \
  'xbacklight -set $(cat /tmp/xidlebacklight); systemctl suspend' '' &
